home_application/urls.py
# -*- coding: utf-8 -*-
"""testapp URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url

from home_application import views

urlpatterns = (
    url(r'^$', views.home),
    url(r'helloworld', views.helloworld),
    url(r'HelloBlueking', views.HelloBlueking),
    url(r'addhost', views.addhost, name="addhost"),
    url(r'get-data', views.api_data, name="api-data"),
    url(r'show_data/(?P<pk>[0-9]+)', views.showdata.as_view(), name="showdata"),
    url(r'quickshow', views.quickshow, name="quickshow"),
    url(r'api/get_dfusage_hsq/$', views.api_disk_usage, name="api-quickshow"),
    url(r'get_usage_data/$', views.get_usage_data,name="get_usage_data"),
    url(r'importdata/$', views.importdata),


)

urls.py
# -*- coding: utf-8 -*-
"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('blueapps.account.urls')),
    # 如果你习惯使用 Django 模板，请在 home_application 里开发你的应用，
    # 这里的 home_application 可以改成你想要的名字
    url(r'^', include('home_application.urls')),
    # 如果你习惯使用 mako 模板，请在 mako_application 里开发你的应用，
    # 这里的 mako_application 可以改成你想要的名字
    url(r'^mako/', include('mako_application.urls')),
    url(r'^hsq/', include('home_application.urls',namespace="hsq")),

]

home_application/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
systemname = (
    (str('1'),'linux'),
    (str('2'),'windows'),
    (str('3'),'other'),
)

class HostInfo(models.Model):
    ip = models.GenericIPAddressField('ip',unique=True)
    osname = models.CharField('系统名称',max_length=20,choices=systemname,blank=True,null=True)
    prartition = models.CharField("分区情况描述",max_length=200,blank=True,null=True)

    def __str__(self):
        return self.ip

class DiskUsage(models.Model):
    host = models.ForeignKey('HostInfo')
    value = models.CharField('磁盘使用率',max_length=20)
    add_time = models.DateTimeField('录入时间', auto_now=True)

home_application/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ImproperlyConfigured
import json

from home_application.models import *
from django.views.generic import TemplateView, View, ListView, DetailView
from blueking.component.shortcuts import get_client_by_request
from blueapps.account.decorators import login_exempt

import time


# 开发框架中通过中间件默认是需要登录态的，如有不需要登录的，可添加装饰器login_exempt
# 装饰器引入 from blueapps.account.decorators import login_exempt
def home(request):
    """
    首页
    """
    return render(request, 'home_application/home.html')


def helloworld(request):
    return render(request, 'home_application/helloworld.html')


@csrf_exempt
def HelloBlueking(request):
    if request.POST and request.POST.get('inputid'):
        print(request.POST.get('inputid'))
        if request.POST.get('inputid') == 'Hello Blueking':
            dis = 'Congratulation！'
        else:
            dis = '请输入正确的内容：'
        return JsonResponse({'data': dis})
    return render(request, 'home_application/HelloBlueking.html')


@csrf_exempt
def addhost(request):
    if request.method == 'GET':
        return render(request, 'home_application/addhost.html')
    if request.method == 'POST':
        try:
            addinfo = HostInfo(ip=request.POST.get('ip', None),
                               osname=request.POST.get('os', None),
                               prartition=request.POST.get('part', None),
                               )
            addinfo.save()
            msg = {"msg": "data is save"}
        except Exception as e:
            msg = {"msg": "error " + e[1]}
        return JsonResponse(msg)


def quickshow(request):
    if request.method == 'GET':
        hostqueryset = HostInfo.objects.all()
        return render(request, 'home_application/quickshow.html', locals())


def api_data(request):
    fieldlist = ['id', 'ip', 'osname', 'prartition']
    qs = HostInfo.objects.all()
    prelist = [[getattr(i, x) for x in fieldlist] for i in qs]

    jsondata = {"data": prelist}
    return JsonResponse(jsondata)


class showdata(ListView):
    context_object_name = 'usedisk'
    template_name = 'home_application/showdata.html'
    model = DiskUsage


@csrf_exempt
def get_usage_data(request):
    """
    调用自主接入接口api
    """
    if request.method == 'POST':
        client = get_client_by_request(request)
        kwargs = request.body
        kwargs = json.loads(request.body)
        kwargs['bk_username'] = '314629925'
        usage = client.hsq.get_dfusage_hsq(kwargs)
        return JsonResponse(usage)
    if request.method == 'GET':
        return render(request, "home_application/get_usage_data.html")


@login_exempt
def api_disk_usage(request):
    """
    磁盘使用率API接口 api/get_dfusage_xxx
    """
    ip = request.GET.get('ip', '')
    system = request.GET.get('system', '')
    mounted = request.GET.get('disk', '')
    if ip and system and mounted:
        _data = HostInfo.objects.get(ip=ip, )

    else:
        return JsonResponse({
            "result": False,
            "data": [],
            "message": '参数不完整'
        })

    data_list = []

    disk_usages = _data.diskusage_set.all()
    res = model_data_format(disk_usages)

    data_list.append(
        {
            'ip': _data.ip,
            'system': _data.osname,
            'mounted': _data.prartition,
            'disk_usage': [res]


        }
    )

    return JsonResponse({
        "result": True,
        "data": data_list,
        "message": 'ok'
    })


def model_data_format(usages):
    res = []
    for usage in usages:
        res.append([usage.host.ip, usage.value, usage.add_time])
    return res


@login_exempt
def importdata(request):
    host = HostInfo.objects.get(ip='10.0.1.80')
    for i in range(10):
        sv = DiskUsage(host=host, value='7%')
        sv.save()
        time.sleep(5)

home_application/templates/home_application/addhost.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- 若您需要使用Kendo UI Professional，请联系版权人获得合法的授权或许可。 -->
    <!-- Bootstrap css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css"
          rel="stylesheet">
    <!-- kendo ui css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.common.min.css"
          rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.default.min.css"
          rel="stylesheet">
    <!-- font-awesome -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/fontawesome/css/font-awesome.css" rel="stylesheet">
    <!--蓝鲸提供的公用样式库 -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk_pack.css" rel="stylesheet">
    <!-- 如果要使用Bootstrap的js插件，必须先调入jQuery -->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <!-- 包括所有bootstrap的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <!-- 包括所有kendoui的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/js/kendo.all.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/bk/js/bk.js"></script>
    <!-- 数据埋点统计 -->
    <script src="http://magicbox.bk.tencent.com/static_api/analysis.js"></script>
    <!-- 以下两个插件用于在IE8以及以下版本浏览器支持HTML5元素和媒体查询，如果不需要用可以移除 -->
    <!--[if lt IE 9]><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/html5shiv.min.js"></script><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/respond.min.js"></script>
    <![endif]-->
    <!-- datatable 引用 -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/dataTables.bootstrap.css"
          rel="stylesheet"/>

    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/jquery.dataTables.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/dataTables.bootstrap.js"></script>

</head>

<body class="bg-bright3" data-bg-color="bg-bright3">
<div class="king-page-box">
    <div class="king-layout1-header">
        <nav class="">
            <div style="overflow:hidden; z-index: inherit;" class="navbar king-horizontal-nav1  f14">
                <div class="navbar-container">
                    <div class="navbar-header pull-left">
                        <a class="navbar-brand" href="javascript:;">
                            <img src="https://magicbox.bk.tencent.com/static_api/v3/bk/images/logo.png" class="logo">
                        </a>
                    </div>
                    <ul class="nav navbar-nav pull-left m0">
                        <li class="active"><a href="javascript:void(0);">首页</a></li>
                        <li><a href="javascript:void(0);">关于我们</a></li>
                        <li><a href="javascript:void(0);">联系我们</a></li>
                    </ul>
                    <div class="navbar-header pull-right">
                        <ul class="nav">
                            <li class="user-info">
                                <a href="javascript:;">
                                    <img class="img-rounded"
                                         src="https://magicbox.bk.tencent.com/static_api/v3/components/horizontal_nav1/images/avatar.png">
                                    <span>admin</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="king-layout1-main clearfix">
        <!-- sidebar start -->
        <div class="king-layout1-sidebar" style="width:216px;">
            <nav>
                <div class="king-vertical-nav6   ">
                    <div>
                        <div class="nav-header">
                            <span class="glyphicon fa fa-fw fa-dashboard logo"></span>
                            <span>添加主机</span>
                        </div>
                        <ul class="nav-list"></ul>
                    </div>
                </div>
            </nav>
        </div>
        <!-- sidebar end -->
        <!-- content start -->
        <div class="king-content-wrap">
            <div class="king-layout1-content" style="margin-left: 216px;">
                <!-- <div class="king-page-topbar pl20 pr20 {{ marginStyle }}"> -->
                <div class="king-page-topbar ">
                    <h3 class="king-topbar-title mb0">
                        <span></span>
                    </h3>
                    <ul class="breadcrumb king-breadcrumb pl0 bg-transparent">
                        <li><a href="javascript:void(0);">首页</a></li>
                        <li class="active"><a href="javascript:void(0);">添加主机</a></li>
                    </ul>
                </div>
                <!-- 面板 编辑 开始 -->
                <!-- 面板 编辑 结束 -->
                <div class="panel panel-default mb0">
                    <div class="panel-heading"> 增加</div>
                    <div class="panel-body">
                        <form class="form-horizontal">
                            <div class="form-group clearfix ">
                                <label class="col-sm-3 control-label bk-lh30 pt0">ip：</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control bk-valign-top" id="ipaddr"
                                           placeholder="请输入ip"></div>
                            </div>
                            <div class="form-group clearfix f12">
                                <label class="col-sm-3 control-label bk-lh30 pt0">操作系统：</label>
                                <div class="col-sm-9">
                                    <select name="" id="osselect" class="form-control bk-valign-top">
                                        <option value="linux">linux</option>
                                        <option value="windows">windows</option>
                                        <option value="其它">其它</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group clearfix ">
                                <label class="col-sm-3 control-label bk-lh30 pt0">分区情况：</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control bk-valign-top" id="prartition"
                                           placeholder="请输入分区情况"></div>
                            </div>
                            <br>
                            <div class="form-group text-center">
                                <button type="button" class="king-btn mr10  king-info" id="submit">提交</button>
                                <button type="reset" class="king-btn king-default">取消</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="king-block king-block-bordered king-block-themed mb0">
                    <div class="king-block-header king-info">
                        <ul class="king-block-options">
                            <li>
                                <!-- <button type="button"><i class="fa fa-cog"></i></button> -->
                            </li>
                        </ul>
                        <h3 class="king-block-title">展示</h3>
                    </div>
                    <div class="king-block-content">


                        <table id="table2_demo2" class="table table-bordered table-striped dataTable no-footer"
                               role="grid" aria-describedby="table2_demo2_info"></table>
                        <!-- 设置面板End -->
                    </div>
                </div>


            </div>
        </div>
        <!-- content end -->
    </div>
</div>
</body>
<!--
如果没有引用以下文件，请去掉此注释
<link href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/dataTables.bootstrap.css" rel="stylesheet"/>
<link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk.css" rel="stylesheet">
<script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
<script src="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/jquery.dataTables.js"></script>
<script src="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/dataTables.bootstrap.js"></script>
-->
<script type="text/javascript">
    //表格(DataTables)-2，使用数组数据源
    var language = {
        search: '搜索：',
        lengthMenu: "每页显示 _MENU_ 记录",
        zeroRecords: "没找到相应的数据！",
        info: "分页 _PAGE_ / _PAGES_",
        infoEmpty: "暂无数据！",
        infoFiltered: "(从 _MAX_ 条数据中搜索)",
        paginate: {
            first: '首页',
            last: '尾页',
            previous: '上一页',
            next: '下一页',
        }
    }


    let table = $('#table2_demo2').dataTable({
        {#processing: true,#}
        lengthMenu: [9, 10, 20, 50, 100, 500],
        {#serverSide: true,#}
        headers: {
            Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3"
        },
        lengthChange: false, //不允许用户改变表格每页显示的记录数
        searching: false, //关闭搜索
        language: language, //汉化
        pageLength: 5, //每页显示几条数据
        pagingType: 'go_page',
        ajax: {
            "url": "{% url "hsq:api-data" %}",
            type: "GET",

        },

        columns: [
            {title: 'ip'},
            {title: '操作系统'},
            {title: '分区情况'}
        ]
    });
</script>

<script>
    $("#submit").on("click", function () {
        $.ajax(
            {
                type: "POST",
                url: "{% url "hsq:addhost" %}",
                data: {
                    "ip": $("#ipaddr").val(),
                    "os": $("#osselect").val(),
                    "part": $("#prartition").val()
                },
                success: function (msg) {
                    alert("Data Saved: " + msg.msg);
                    location.reload()
                }
            }
        )

    })
</script>


</html>

home_application/templates/home_application/quickshow.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>

    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/base/common.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/fontawesome/css/font-awesome.min.css"
          rel="stylesheet">
    <!-- 若您需要使用Kendo UI Professional，请联系版权人获得合法的授权或许可。 -->
    <!-- Bootstrap css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css"
          rel="stylesheet">
    <!-- kendo ui css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.common.min.css"
          rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.default.min.css"
          rel="stylesheet">
    <!-- font-awesome -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/fontawesome/css/font-awesome.css" rel="stylesheet">
    <!--蓝鲸提供的公用样式库 -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk_pack.css" rel="stylesheet">
    <!-- 如果要使用Bootstrap的js插件，必须先调入jQuery -->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <!-- 包括所有bootstrap的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <!-- 包括所有kendoui的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/js/kendo.all.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/bk/js/bk.js"></script>
    <!-- 数据埋点统计 -->
    <script src="http://magicbox.bk.tencent.com/static_api/analysis.js"></script>
    <!-- 以下两个插件用于在IE8以及以下版本浏览器支持HTML5元素和媒体查询，如果不需要用可以移除 -->
    <!--[if lt IE 9]><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/html5shiv.min.js"></script><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/respond.min.js"></script>
    <![endif]-->
    <!-- datatable 引用 -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/dataTables.bootstrap.css"
          rel="stylesheet"/>

    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/jquery.dataTables.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/dataTables.bootstrap.js"></script>

</head>

<body class="bg-bright3" data-bg-color="bg-bright3">
<div class="king-page-box">
    <div class="king-layout1-header">
        <nav class="">
            <div style="overflow:hidden; z-index: inherit;" class="navbar king-horizontal-nav1  f14">
                <div class="navbar-container">
                    <div class="navbar-header pull-left">
                        <a class="navbar-brand" href="javascript:;">
                            <img src="https://magicbox.bk.tencent.com/static_api/v3/bk/images/logo.png" class="logo">
                        </a>
                    </div>
                    <ul class="nav navbar-nav pull-left m0">
                        <li class="active"><a href="javascript:void(0);">首页</a></li>
                        <li><a href="javascript:void(0);">关于我们</a></li>
                        <li><a href="javascript:void(0);">联系我们</a></li>
                    </ul>
                    <div class="navbar-header pull-right">
                        <ul class="nav">
                            <li class="user-info">
                                <a href="javascript:;">
                                    <img class="img-rounded"
                                         src="https://magicbox.bk.tencent.com/static_api/v3/components/horizontal_nav1/images/avatar.png">
                                    <span>admin</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="king-layout1-main clearfix">
        <!-- sidebar start -->
        <div class="king-layout1-sidebar" style="width:216px;">
            <nav>
                <div class="king-vertical-nav6   ">
                    <div>
                        <div class="nav-header">
                            <span class="glyphicon fa fa-fw fa-dashboard logo"></span>
                            <span>快速展示</span>
                        </div>
                        <ul class="nav-list"></ul>
                    </div>
                </div>
            </nav>
        </div>
        <!-- sidebar end -->
        <!-- content start -->
        <div class="king-content-wrap">
            <div class="king-layout1-content" style="margin-left: 216px;">
                <!-- <div class="king-page-topbar pl20 pr20 {{ marginStyle }}"> -->
                <div class="king-page-topbar ">
                    <h3 class="king-topbar-title mb0">
                        <span></span>
                    </h3>
                    <ul class="breadcrumb king-breadcrumb pl0 bg-transparent">
                        <li><a href="javascript:void(0);">首页</a></li>
                        <li class="active"><a href="javascript:void(0);">快速展示</a></li>
                    </ul>
                </div>
                <!-- 面板 编辑 开始 -->
                <!-- 面板 编辑 结束 -->
                <div class="panel panel-default mb0">

                    <div class="panel-body">
                        <form class="form-horizontal">
                            <div class="form-group clearfix ">
                                <label class="col-sm-3 control-label bk-lh30 pt0">ip：</label>
                                <div class="col-sm-9">
                                    <select name="" id="osselect" class="form-control bk-valign-top">
                                        {% for i in hostqueryset %}
                                            <option value={{ i.id }}>{{ i.ip }}</option>
                                        {% endfor %}

                                    </select>
                                </div>
                            </div>
                            <div class="form-group clearfix f12">
                                <label class="col-sm-3 control-label bk-lh30 pt0">操作系统：</label>
                                <div class="col-sm-9">
                                    <select name="" id="osselect" class="form-control bk-valign-top">
                                        <option value="linux">linux</option>
                                        <option value="windows">windows</option>
                                        <option value="其它">其它</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group clearfix ">
                                <label class="col-sm-3 control-label bk-lh30 pt0">分区路径：</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control bk-valign-top" id="prartition"
                                           placeholder="请输入分区情况"></div>
                            </div>
                            <br>
                            <div class="form-group text-center">
                                <button type="button" class="king-btn mr10  king-info" id="submit-button">提交</button>
                                <button type="reset" class="king-btn king-default">取消</button>
                            </div>


                        </form>
                    </div>
                </div>

                <div class="king-block king-block-bordered king-block-themed mb0">
                    <div class="king-block-header king-info">
                        <ul class="king-block-options">
                            <li>
                                <!-- <button type="button"><i class="fa fa-cog"></i></button> -->
                            </li>
                        </ul>
                        <h3 class="king-block-title">展示</h3>
                    </div>
                    <div>
                        json 展示
                    </div>

                </div>


            </div>
        </div>
        <!-- content end -->
    </div>
</div>
</body>
<!--
如果没有引用以下文件，请去掉此注释
<link href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/dataTables.bootstrap.css" rel="stylesheet"/>
<link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk.css" rel="stylesheet">
<script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
<script src="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/jquery.dataTables.js"></script>
<script src="https://magicbox.bk.tencent.com/static_api/v3/assets/datatables-1.10.7/dataTables.bootstrap.js"></script>
-->


<script>
    $("#submit-button").addEventListener('click', function () {
        var ip = $('#ipaddr').val();
        var system = $('#osselect').val();
        var disk = $('#prartition').val();
        console.log(ip, system, disk);
        let data = {
            'ip': ip,
            'system': system,
            'disk': disk
        };
        $.ajax({
            url: "{% url "hsq:api-quickshow" %}",
            data: JSON.stringify(data),
            type: 'POST',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                if (data['result']) {
                    result_data = data['data'][0];
                    createEStandLineChart({
                        selector: 'chart_1558345623849', // 图表容器
                        data: result_data['disk_usage'], // 图表数据
                    });
                }
            }
        });
    });


    $("#submit").on("click", function () {
        $.ajax(
            {
                type: "POST",
                url: "{% url "hsq:addhost" %}",
                data: {
                    "ip": $("#ipaddr").val(),
                    "os": $("#osselect").val(),
                    "part": $("#prartition").val()
                },
                success: function (msg) {
                    alert("Data Saved: " + msg.msg);
                    location.reload()
                }
            }
        )

    })
</script>


</html>